### ISSUE TITLE
is there a heart emoticon?

### ISSUE THREAD

**Issue by Kreijstal** [Vidabe/tikzsymbols#2]
I would like to use a heart emoticon

**Comment by Vidabe** [comment]
Currently not in this package, but other packages have implemented one (like marvosym e.g.).
You can search several symbols via [detexify](https://detexify.kirelabs.org/classify.html) or in the [comprehensive symbol list](https://ctan.org/pkg/comprehensive).

Hope it helps.

**Comment by Vidabe** [comment]
Added \Heart and \dHeart (a bit late, but early enough for next year).
